spring:
  application:
    name: ${project.artifactId}
  main:
    banner-mode: log
  devtools:
    restart:
      exclude: static/**,public/**
logging:
  level:
    org.fasterxml: "DEBUG"
    org.springframework: "INFO"
    org.hibernate: "INFO"
    org.apache.camel.component.rabbitmq: "INFO"
    org.openpcm: "TRACE"
    org.springframework.security: "DEBUG"
    org.springframework.web.servlet.DispatcherServlet: "DEBUG"
    org.springframework.web.filter.CommonsRequestLoggingFilter: "DEBUG"
  file: ${project.artifactId}.log
server:
  port: 14606
securityDefinitions:
  basicAuth:
    type: basic
      