spring:
  application:
    name: openpcm-service
  main:
    banner-mode: log
  devtools:
    restart:
      exclude: static/**,public/**
logging:
  level:
    org.fasterxml: "DEBUG"
    org.springframework: "INFO"
    org.hibernate: "INFO"
    org.apache.camel.component.rabbitmq: "INFO"
    org.openpcm: "TRACE"
    org.springframework.web.servlet.DispatcherServlet: "DEBUG"
server:
  port: 14606